def apply_template(en_data, data)
  [
    # global
    {
      "key" => ":h[elp] " + data["words"]["keyword"],
      "catcode"=> "global",
      "category"=> data["global"]["title"],
      "desc" => data["global"]["commands"]["helpForKeyword"],
      "search" => en_data["global"]["commands"]["helpForKeyword"],
      "ascript" => 'key code 53//keystroke ":h"//key code 49//keystroke "keyword"',
    },
    {
      "key" => ":sav[eas] " + data["words"]["file"],
      "catcode"=> "global",
      "category"=> data["global"]["title"],
      "desc" => data["global"]["commands"]["saveAsFile"],
      "search" => en_data["global"]["commands"]["saveAsFile"],
      "ascript" => 'key code 53//keystroke ":sav"//key code 49//keystroke "file"',
    },
    {
      "key" => ":clo[se]",
      "catcode"=> "global",
      "category"=> data["global"]["title"],
      "desc" => data["global"]["commands"]["closePane"],
      "search" => en_data["global"]["commands"]["closePane"],
      "ascript" => 'key code 53//keystroke ":clo" & return',
    },
    {
      "key" => ":ter[minal]",
      "catcode"=> "global",
      "category"=> data["global"]["title"],
      "desc" => data["global"]["commands"]["colonTerminal"],
      "search" => en_data["global"]["commands"]["colonTerminal"],
      "ascript" => 'key code 53//keystroke ":ter" & return',
    },
    {
      "key" => "K",
      "catcode"=> "global",
      "category"=> data["global"]["title"],
      "desc" => data["global"]["commands"]["K"],
      "search" => en_data["global"]["commands"]["K"],
      "ascript" => 'key code 53//keystroke "K"',
    },
    #cursorMovement
    {
      "key" => "h",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["h"],
      "search" => en_data["cursorMovement"]["commands"]["h"],
      "ascript" => 'key code 53//keystroke "h"',
    },
    {
      "key" => "j",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["j"],
      "search" => en_data["cursorMovement"]["commands"]["j"],
      "ascript" => 'key code 53//keystroke "j"',
    },
    {
      "key" => "k",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["k"],
      "search" => en_data["cursorMovement"]["commands"]["k"],
      "ascript" => 'key code 53//keystroke "k"',
    },
    {
      "key" => "l",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["l"],
      "search" => en_data["cursorMovement"]["commands"]["l"],
      "ascript" => 'key code 53//keystroke "l"',
    },
    {
      "key" => "gj",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gj"],
      "search" => en_data["cursorMovement"]["commands"]["gj"],
      "ascript" => 'key code 53//keystroke "gj"',
    },
    {
      "key" => "gk",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gk"],
      "search" => en_data["cursorMovement"]["commands"]["gk"],
      "ascript" => 'key code 53//keystroke "gk"',
    },
    {
      "key" => "H",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["H"],
      "search" => en_data["cursorMovement"]["commands"]["H"],
      "ascript" => 'key code 53//keystroke "H"',
    },
    {
      "key" => "M",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["M"],
      "search" => en_data["cursorMovement"]["commands"]["M"],
      "ascript" => 'key code 53//keystroke "M"',
    },
    {
      "key" => "L",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["L"],
      "search" => en_data["cursorMovement"]["commands"]["L"],
      "ascript" => 'key code 53//keystroke "L"',
    },
    {
      "key" => "w",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["w"],
      "search" => en_data["cursorMovement"]["commands"]["w"],
      "ascript" => 'key code 53//keystroke "w"',
    },
    {
      "key" => "W",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["W"],
      "search" => en_data["cursorMovement"]["commands"]["W"],
      "ascript" => 'key code 53//keystroke "W"',
    },
    {
      "key" => "e",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["e"],
      "search" => en_data["cursorMovement"]["commands"]["e"],
      "ascript" => 'key code 53//keystroke "e"',
    },
    {
      "key" => "E",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["E"],
      "search" => en_data["cursorMovement"]["commands"]["E"],
      "ascript" => 'key code 53//keystroke "E"',
    },
    {
      "key" => "b",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["b"],
      "search" => en_data["cursorMovement"]["commands"]["b"],
      "ascript" => 'key code 53//keystroke "b"',
    },
    {
      "key" => "B",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["B"],
      "search" => en_data["cursorMovement"]["commands"]["B"],
      "ascript" => 'key code 53//keystroke "B"',
    },
    {
      "key" => "ge",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["ge"],
      "search" => en_data["cursorMovement"]["commands"]["ge"],
      "ascript" => 'key code 53//keystroke "ge"',
    },
    {
      "key" => "gE",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gE"],
      "search" => en_data["cursorMovement"]["commands"]["gE"],
      "ascript" => 'key code 53//keystroke "gE"',
    },
    {
      "key" => "%",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["percent"],
      "search" => en_data["cursorMovement"]["commands"]["percent"],
      "ascript" => 'key code 53//keystroke "%"',
    },
    {
      "key" => "0",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["zero"],
      "search" => en_data["cursorMovement"]["commands"]["zero"],
      "ascript" => 'key code 53//keystroke "0"',
    },
    {
      "key" => "^",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["caret"],
      "search" => en_data["cursorMovement"]["commands"]["caret"],
      "ascript" => 'key code 53//keystroke "^"',
    },
    {
      "key" => "$",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["dollar"],
      "search" => en_data["cursorMovement"]["commands"]["dollar"],
      "ascript" => 'key code 53//keystroke "$"',
    },
    {
      "key" => "g_",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["g_"],
      "search" => en_data["cursorMovement"]["commands"]["g_"],
      "ascript" => 'key code 53//keystroke "g_"',
    },
    {
      "key" => "gg",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gg"],
      "search" => en_data["cursorMovement"]["commands"]["gg"],
      "ascript" => 'key code 53//keystroke "gg"',
    },
    {
      "key" => "G",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["G"],
      "search" => en_data["cursorMovement"]["commands"]["G"],
      "ascript" => 'key code 53//keystroke "G"',
    },
    {
      "key" => "5gg or 5G",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["fiveG"],
      "search" => en_data["cursorMovement"]["commands"]["fiveG"],
      "ascript" => 'key code 53//keystroke "5gg"',
    },
    {
      "key" => "gd",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gd"],
      "search" => en_data["cursorMovement"]["commands"]["gd"],
      "ascript" => 'key code 53//keystroke "gd"',
    },
    {
      "key" => "gD",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["gD"],
      "search" => en_data["cursorMovement"]["commands"]["gD"],
      "ascript" => 'key code 53//keystroke "gD"',
    },
    {
      "key" => "fx",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["fx"],
      "search" => en_data["cursorMovement"]["commands"]["fx"],
      "ascript" => 'key code 53//keystroke "fx"',
    },
    {
      "key" => "tx",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["tx"],
      "search" => en_data["cursorMovement"]["commands"]["tx"],
      "ascript" => 'key code 53//keystroke "tx"',
    },
    {
      "key" => "Fx",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["Fx"],
      "search" => en_data["cursorMovement"]["commands"]["Fx"],
      "ascript" => 'key code 53//keystroke "Fx"',
    },
    {
      "key" => "Tx",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["Tx"],
      "search" => en_data["cursorMovement"]["commands"]["Tx"],
      "ascript" => 'key code 53//keystroke "Tx"',
    },
    {
      "key" => ";",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["semicolon"],
      "search" => en_data["cursorMovement"]["commands"]["semicolon"],
      "ascript" => 'key code 53//keystroke ";"',
    },
    {
      "key" => ",",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["comma"],
      "search" => en_data["cursorMovement"]["commands"]["comma"],
      "ascript" => 'key code 53//keystroke ","',
    },
    {
      "key" => "}",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["closeCurlyBrace"],
      "search" => en_data["cursorMovement"]["commands"]["closeCurlyBrace"],
      "ascript" => 'key code 53//keystroke "}"',
    },
    {
      "key" => "{",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["openCurlyBrace"],
      "search" => en_data["cursorMovement"]["commands"]["openCurlyBrace"],
      "ascript" => 'key code 53//keystroke "{"',
    },
    {
      "key" => "zz",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["centerCursor"],
      "search" => en_data["cursorMovement"]["commands"]["centerCursor"],
      "ascript" => 'key code 53//keystroke "zz"',
    },
    {
      "key" => "Ctrl+e",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPluse"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPluse"],
      "ascript" => 'key code 53//keystroke "e" using control down',
    },
    {
      "key" => "Ctrl+y",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPlusy"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPlusy"],
      "ascript" => 'key code 53//keystroke "y" using control down',
    },
    {
      "key" => "Ctrl+b",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPlusb"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPlusb"],
      "ascript" => 'key code 53//keystroke "b" using control down',
    },
    {
      "key" => "Ctrl+f",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPlusf"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPlusf"],
      "ascript" => 'key code 53//keystroke "f" using control down',
    },
    {
      "key" => "Ctrl+u",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPlusu"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPlusu"],
      "ascript" => 'key code 53//keystroke "u" using control down',
    },
    {
      "key" => "Ctrl+d",
      "catcode"=> "cursorMovement",
      "category"=> data["cursorMovement"]["title"],
      "desc" => data["cursorMovement"]["commands"]["CtrlPlusd"],
      "search" => en_data["cursorMovement"]["commands"]["CtrlPlusd"],
      "ascript" => 'key code 53//keystroke "d" using control down',
    },
    # 'insertMode
    {
      "key" => "i",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["i"],
      "search" => en_data["insertMode"]["commands"]["i"],
      "ascript" => 'key code 53//keystroke "i"',
    },
    {
      "key" => "I",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["I"],
      "search" => en_data["insertMode"]["commands"]["I"],
      "ascript" => 'key code 53//keystroke "I"',
    },
    {
      "key" => "a",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["a"],
      "search" => en_data["insertMode"]["commands"]["a"],
      "ascript" => 'key code 53//keystroke "a"',
    },
    {
      "key" => "A",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["A"],
      "search" => en_data["insertMode"]["commands"]["A"],
      "ascript" => 'key code 53//keystroke "A"',
    },
    {
      "key" => "o",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["o"],
      "search" => en_data["insertMode"]["commands"]["o"],
      "ascript" => 'key code 53//keystroke "o"',
    },
    {
      "key" => "O",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["O"],
      "search" => en_data["insertMode"]["commands"]["O"],
      "ascript" => 'key code 53//keystroke "O"',
    },
    {
      "key" => "ea",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ea"],
      "search" => en_data["insertMode"]["commands"]["ea"],
      "ascript" => 'key code 53//keystroke "ea"',
    },
    {
      "key" => "Ctrl+h",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlush"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlush"],
      "ascript" => 'keystroke "h" using control down',
    },
    {
      "key" => "Ctrl+w",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusw"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusw"],
      "ascript" => 'keystroke "w" using control down',
    },
    {
      "key" => "Ctrl+j",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusj"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusj"],
      "ascript" => 'keystroke "j" using control down',
    },
    {
      "key" => "Ctrl+t",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlust"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlust"],
      "ascript" => 'keystroke "t" using control down',
    },
    {
      "key" => "Ctrl+d",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusd"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusd"],
      "ascript" => 'keystroke "d" using control down',
    },
    {
      "key" => "Ctrl+n",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusn"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusn"],
      "ascript" => 'keystroke "n" using control down',
    },
    {
      "key" => "Ctrl+p",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusp"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusp"],
      "ascript" => 'keystroke "p" using control down',
    },
    {
      "key" => "Ctrl+r x",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusrx"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusrx"],
      "ascript" => 'keystroke "r" using control down//keystroke "x"',
    },
    {
      "key" => "Ctrl+o x",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["ctrlPlusox"],
      "search" => en_data["insertMode"]["commands"]["ctrlPlusox"],
      "ascript" => 'keystroke "o" using control down//keystroke "x"',
    },
    {
      "key" => "Esc",
      "catcode"=> "insertMode",
      "category"=> data["insertMode"]["title"],
      "desc" => data["insertMode"]["commands"]["Esc"],
      "search" => en_data["insertMode"]["commands"]["Esc"],
      "ascript" => 'key code 53',
    },
    # 'editing
    {
      "key" => "r",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["r"],
      "search" => en_data["editing"]["commands"]["r"],
      "ascript" => 'key code 53//keystroke "r"',
    },
    {
      "key" => "R",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["R"],
      "search" => en_data["editing"]["commands"]["R"],
      "ascript" => 'key code 53//keystroke "R"',
    },
    {
      "key" => "J",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["J"],
      "search" => en_data["editing"]["commands"]["J"],
      "ascript" => 'key code 53//keystroke "J"',
    },
    {
      "key" => "gJ",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["gJ"],
      "search" => en_data["editing"]["commands"]["gJ"],
      "ascript" => 'key code 53//keystroke "gJ"',
    },
    {
      "key" => "gwip",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["gwip"],
      "search" => en_data["editing"]["commands"]["gwip"],
      "ascript" => 'key code 53//keystroke "gwip"',
    },
    {
      "key" => "g~",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["gTilde"],
      "search" => en_data["editing"]["commands"]["gTilde"],
      "ascript" => 'key code 53//keystroke "g~"',
    },
    {
      "key" => "gu",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["gu"],
      "search" => en_data["editing"]["commands"]["gu"],
      "ascript" => 'key code 53//keystroke "gu"',
    },
    {
      "key" => "gU",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["gU"],
      "search" => en_data["editing"]["commands"]["gU"],
      "ascript" => 'key code 53//keystroke "gU"',
    },
    {
      "key" => "cc",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["cc"],
      "search" => en_data["editing"]["commands"]["cc"],
      "ascript" => 'key code 53//keystroke "cc"',
    },
    {
      "key" => "c$ or C",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["cDollar"],
      "search" => en_data["editing"]["commands"]["cDollar"],
      "ascript" => 'key code 53//keystroke "g$"',
    },
    {
      "key" => "ciw",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["ciw"],
      "search" => en_data["editing"]["commands"]["ciw"],
      "ascript" => 'key code 53//keystroke "ciw"',
    },
    {
      "key" => "cw or ce",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["cw"],
      "search" => en_data["editing"]["commands"]["cw"],
      "ascript" => 'key code 53//keystroke "cw"',
    },
    {
      "key" => "s",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["s"],
      "search" => en_data["editing"]["commands"]["s"],
      "ascript" => 'key code 53//keystroke "s"',
    },
    {
      "key" => "S",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["S"],
      "search" => en_data["editing"]["commands"]["S"],
      "ascript" => 'key code 53//keystroke "S"',
    },
    {
      "key" => "xp",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["xp"],
      "search" => en_data["editing"]["commands"]["xp"],
      "ascript" => 'key code 53//keystroke "xp"',
    },
    {
      "key" => "u",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["u"],
      "search" => en_data["editing"]["commands"]["u"],
      "ascript" => 'key code 53//keystroke "u"',
    },
    {
      "key" => "U",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["U"],
      "search" => en_data["editing"]["commands"]["U"],
      "ascript" => 'key code 53//keystroke "U"',
    },
    {
      "key" => "Ctrl+r",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["CtrlPlusr"],
      "search" => en_data["editing"]["commands"]["CtrlPlusr"],
      "ascript" => 'key code 53//keystroke "r" using control down',
    },
    {
      "key" => ".",
      "catcode"=> "editing",
      "category"=> data["editing"]["title"],
      "desc" => data["editing"]["commands"]["dot"],
      "search" => en_data["editing"]["commands"]["dot"],
      "ascript" => 'key code 53//keystroke "."',
    },
    # 'markingText
    {
      "key" => "v",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["v"],
      "search" => en_data["markingText"]["commands"]["v"],
      "ascript" => 'key code 53//keystroke "v"',
    },
    {
      "key" => "V",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["V"],
      "search" => en_data["markingText"]["commands"]["V"],
      "ascript" => 'key code 53//keystroke "V"',
    },
    {
      "key" => "o",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["o"],
      "search" => en_data["markingText"]["commands"]["o"],
      "ascript" => 'key code 53//keystroke "o"',
    },
    {
      "key" => "Ctrl+v",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["CtrlPlusv"],
      "search" => en_data["markingText"]["commands"]["CtrlPlusv"],
      "ascript" => 'key code 53//keystroke "v" using control down',
    },
    {
      "key" => "O",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["O"],
      "search" => en_data["markingText"]["commands"]["O"],
      "ascript" => 'key code 53//keystroke "O"',
    },
    {
      "key" => "aw",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["aw"],
      "search" => en_data["markingText"]["commands"]["aw"],
      "ascript" => 'key code 53//keystroke "aw"',
    },
    {
      "key" => "ab",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["ab"],
      "search" => en_data["markingText"]["commands"]["ab"],
      "ascript" => 'key code 53//keystroke "ab"',
    },
    {
      "key" => "aB",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["aB"],
      "search" => en_data["markingText"]["commands"]["aB"],
      "ascript" => 'key code 53//keystroke "aB"', },
    {
      "key" => "at",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["at"],
      "search" => en_data["markingText"]["commands"]["at"],
      "ascript" => 'key code 53//keystroke "at"',
    },
    {
      "key" => "ib",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["ib"],
      "search" => en_data["markingText"]["commands"]["ib"],
      "ascript" => 'key code 53//keystroke "ib"',
    },
    {
      "key" => "iB",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["iB"],
      "search" => en_data["markingText"]["commands"]["iB"],
      "ascript" => 'key code 53//keystroke "iB"',
    },
    {
      "key" => "it",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["it"],
      "search" => en_data["markingText"]["commands"]["it"],
      "ascript" => 'key code 53//keystroke "it"',
    },
    {
      "key" => "Esc",
      "catcode"=> "markingText",
      "category"=> data["markingText"]["title"],
      "desc" => data["markingText"]["commands"]["Esc"],
      "search" => en_data["markingText"]["commands"]["Esc"],
      "ascript" => 'key code 53//key code 53',
    },
    # 'visualCommands
    {
      "key" => ">",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["greaterThan"],
      "search" => en_data["visualCommands"]["commands"]["greaterThan"],
      "ascript" => 'keystroke ">"',
      "ref_only" => true,
    },
    {
      "key" => "<",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["lessThan"],
      "search" => en_data["visualCommands"]["commands"]["lessThan"],
      "ascript" => 'keystroke "<"',
      "ref_only" => true,
    },
    {
      "key" => "y",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["y"],
      "search" => en_data["visualCommands"]["commands"]["y"],
      "ascript" => 'keystroke "y"',
      "ref_only" => true,
    },
    {
      "key" => "d",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["d"],
      "search" => en_data["visualCommands"]["commands"]["d"],
      "ascript" => 'keystroke "d"',
      "ref_only" => true,
    },
    {
      "key" => "~",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["tilde"],
      "search" => en_data["visualCommands"]["commands"]["tilde"],
      "ascript" => 'keystroke "~"',
      "ref_only" => true,
    },
    {
      "key" => "u",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["u"],
      "search" => en_data["visualCommands"]["commands"]["u"],
      "ascript" => 'keystroke "u"',
      "ref_only" => true,
    },
    {
      "key" => "U",
      "catcode"=> "visualCommands",
      "category"=> data["visualCommands"]["title"],
      "desc" => data["visualCommands"]["commands"]["U"],
      "search" => en_data["visualCommands"]["commands"]["U"],
      "ascript" => 'keystroke "U"',
      "ref_only" => true,
    },
    # 'registers
    {
      "key" => ":reg[isters]",
      "catcode"=> "registers",
      "category"=> data["registers"]["title"],
      "desc" => data["registers"]["commands"]["show"],
      "search" => en_data["registers"]["commands"]["show"],
      "ascript" => 'key code 53//keystroke ":reg" & return',
    },
    {
      "key" => "xy",
      "catcode"=> "registers",
      "category"=> data["registers"]["title"],
      "desc" => data["registers"]["commands"]["yankIntoRegisterX"],
      "search" => en_data["registers"]["commands"]["yankIntoRegisterX"],
      "ascript" => 'key code 53//keystroke "xy"',
    },
    {
      "key" => "xp",
      "catcode"=> "registers",
      "category"=> data["registers"]["title"],
      "desc" => data["registers"]["commands"]["pasteRegisterX"],
      "search" => en_data["registers"]["commands"]["pasteRegisterX"],
      "ascript" => 'key code 53//keystroke "xp"',
    },
    {
      "key" => "+y",
      "catcode"=> "registers",
      "category"=> data["registers"]["title"],
      "desc" => data["registers"]["commands"]["quotePlusy"],
      "search" => en_data["registers"]["commands"]["quotePlusy"],
      "ascript" => 'key code 53//keystroke "+y"',
    },
    {
      "key" => "+p",
      "catcode"=> "registers",
      "category"=> data["registers"]["title"],
      "desc" => data["registers"]["commands"]["quotePlusp"],
      "search" => en_data["registers"]["commands"]["quotePlusp"],
      "ascript" => 'key code 53//keystroke "+p"',
    },
    # 'marks
    {
      "key" => "ma",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["currentPositionA"],
      "search" => en_data["marks"]["commands"]["currentPositionA"],
      "ascript" => 'key code 53//keystroke "ma"',
    },
    {
      "key" => "`a",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["jumpPositionA"],
      "search" => en_data["marks"]["commands"]["jumpPositionA"],
      "ascript" => 'key code 53//keystroke "`a"',
    },
    {
      "key" => "y`a",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["yankToMarkA"],
      "search" => en_data["marks"]["commands"]["yankToMarkA"],
      "ascript" => 'key code 53//keystroke "y`a"',
    },
    {
      "key" => "`0",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["backtick0"],
      "search" => en_data["marks"]["commands"]["backtick0"],
      "ascript" => 'key code 53//keystroke "`0"',
    },
    {
      "key" => '`"',
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["backtickQuote"],
      "search" => en_data["marks"]["commands"]["backtickQuote"],
      "ascript" => 'key code 53//keystroke "`\""',
    },
    {
      "key" => "`.",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["backtickDot"],
      "search" => en_data["marks"]["commands"]["backtickDot"],
      "ascript" => 'key code 53//keystroke "`."',
    },
    {
      "key" => "``",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["backtickBacktick"],
      "search" => en_data["marks"]["commands"]["backtickBacktick"],
      "ascript" => 'key code 53//keystroke "``"',
    },
    {
      "key" => ":ju[mps]",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["colonjumps"],
      "search" => en_data["marks"]["commands"]["colonjumps"],
      "ascript" => 'key code 53//keystroke ":ju" & return',
    },
    {
      "key" => "Ctrl+i",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["ctrlPlusi"],
      "search" => en_data["marks"]["commands"]["ctrlPlusi"],
      "ascript" => 'key code 53//keystroke "i" using control down',
    },
    {
      "key" => "Ctrl+o",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["ctrlPluso"],
      "search" => en_data["marks"]["commands"]["ctrlPluso"],
      "ascript" => 'key code 53//keystroke "o" using control down',
    },
    {
      "key" => ":changes",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["colonchanges"],
      "search" => en_data["marks"]["commands"]["colonchanges"],
      "ascript" => 'key code 53//keystroke ":changes" & return',
    },
    {
      "key" => "g,",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["gcomma"],
      "search" => en_data["marks"]["commands"]["gcomma"],
      "ascript" => 'key code 53//keystroke "g,"',
    },
    {
      "key" => "g;",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["gsemicolon"],
      "search" => en_data["marks"]["commands"]["gsemicolon"],
      "ascript" => 'key code 53//keystroke "g;"',
    },
    {
      "key" => "Ctrl+]",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["ctrlPlusCloseSquare"],
      "search" => en_data["marks"]["commands"]["ctrlPlusCloseSquare"],
      "ascript" => 'key code 53//keystroke "]" using control down',
    },
    {
      "key" => "gf",
      "catcode"=> "marks",
      "category"=> data["marks"]["title"],
      "desc" => data["marks"]["commands"]["gf"],
      "search" => en_data["marks"]["commands"]["gf"],
      "ascript" => 'key code 53//keystroke "gf"',
    },
    # 'macros
    {
      "key" => "qa",
      "catcode"=> "macros",
      "category"=> data["macros"]["title"],
      "desc" => data["macros"]["commands"]["recordA"],
      "search" => en_data["macros"]["commands"]["recordA"],
      "ascript" => 'key code 53//keystroke "qa"',
    },
    {
      "key" => "q",
      "catcode"=> "macros",
      "category"=> data["macros"]["title"],
      "desc" => data["macros"]["commands"]["stopRecording"],
      "search" => en_data["macros"]["commands"]["stopRecording"],
      "ascript" => 'key code 53//keystroke "q"',
    },
    {
      "key" => "@a",
      "catcode"=> "macros",
      "category"=> data["macros"]["title"],
      "desc" => data["macros"]["commands"]["runA"],
      "search" => en_data["macros"]["commands"]["runA"],
      "ascript" => 'key code 53//keystroke "@a"',
    },
    {
      "key" => "@@",
      "catcode"=> "macros",
      "category"=> data["macros"]["title"],
      "desc" => data["macros"]["commands"]["rerun"],
      "search" => en_data["macros"]["commands"]["rerun"],
      "ascript" => 'key code 53//keystroke "@@"',
    },

    # 'cutAndPaste
    {
      "key" => "yy",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["yy"],
      "search" => en_data["cutAndPaste"]["commands"]["yy"],
      "ascript" => 'key code 53//keystroke "yy"',
    },
    {
      "key" => "2yy",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["twoyy"],
      "search" => en_data["cutAndPaste"]["commands"]["twoyy"],
      "ascript" => 'key code 53//keystroke "2yy"',
    },
    {
      "key" => "yw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["yw"],
      "search" => en_data["cutAndPaste"]["commands"]["yw"],
      "ascript" => 'key code 53//keystroke "yw"',
    },
    {
      "key" => "yiw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["yiw"],
      "search" => en_data["cutAndPaste"]["commands"]["yiw"],
      "ascript" => 'key code 53//keystroke "yiw"',
    },
    {
      "key" => "yaw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["yaw"],
      "search" => en_data["cutAndPaste"]["commands"]["yaw"],
      "ascript" => 'key code 53//keystroke "yaw"',
    },
    {
      "key" => "y$",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["yDollar"],
      "search" => en_data["cutAndPaste"]["commands"]["yDollar"],
      "ascript" => 'key code 53//keystroke "y$"',
    },
    {
      "key" => "p",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["p"],
      "search" => en_data["cutAndPaste"]["commands"]["p"],
      "ascript" => 'key code 53//keystroke "p"',
    },
    {
      "key" => "P",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["P"],
      "search" => en_data["cutAndPaste"]["commands"]["P"],
      "ascript" => 'key code 53//keystroke "P"',
    },
    {
      "key" => "gp",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["gp"],
      "search" => en_data["cutAndPaste"]["commands"]["gp"],
      "ascript" => 'key code 53//keystroke "gp"',
    },
    {
      "key" => "gP",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["gP"],
      "search" => en_data["cutAndPaste"]["commands"]["gP"],
      "ascript" => 'key code 53//keystroke "gP"',
    },
    {
      "key" => "dd",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["dd"],
      "search" => en_data["cutAndPaste"]["commands"]["dd"],
      "ascript" => 'key code 53//keystroke "dd"',
    },
    {
      "key" => "2dd",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["twodd"],
      "search" => en_data["cutAndPaste"]["commands"]["twodd"],
      "ascript" => 'key code 53//keystroke "2dd"',
    },
    {
      "key" => "dw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["dw"],
      "search" => en_data["cutAndPaste"]["commands"]["dw"],
      "ascript" => 'key code 53//keystroke "dw"',
    },
    {
      "key" => "diw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["diw"],
      "search" => en_data["cutAndPaste"]["commands"]["diw"],
      "ascript" => 'key code 53//keystroke "diw"',
    },
    {
      "key" => "daw",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["daw"],
      "search" => en_data["cutAndPaste"]["commands"]["daw"],
      "ascript" => 'key code 53//keystroke "daw"',
    },
    {
      "key" => "d$ or D",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["dDollar"],
      "search" => en_data["cutAndPaste"]["commands"]["dDollar"],
      "ascript" => 'key code 53//keystroke "d$"',
    },
    {
      "key" => "x",
      "catcode"=> "cutAndPaste",
      "category"=> data["cutAndPaste"]["title"],
      "desc" => data["cutAndPaste"]["commands"]["x"],
      "search" => en_data["cutAndPaste"]["commands"]["x"],
      "ascript" => 'key code 53//keystroke "x"',
    },
    # 'indentText
    {
      "key" => ">>",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["greaterThanGreaterThan"],
      "search" => en_data["indentText"]["commands"]["greaterThanGreaterThan"],
      "ascript" => 'key code 53//keystroke ">>"',
    },
    {
      "key" => "<<",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["lessThanLessThan"],
      "search" => en_data["indentText"]["commands"]["lessThanLessThan"],
      "ascript" => 'key code 53//keystroke "<<"',
    },
    {
      "key" => ">%",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["greaterThanPercent"],
      "search" => en_data["indentText"]["commands"]["greaterThanPercent"],
      "ascript" => 'key code 53//keystroke ">%"',
    },
    {
      "key" => ">ib",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["greaterThanib"],
      "search" => en_data["indentText"]["commands"]["greaterThanib"],
      "ascript" => 'key code 53//keystroke ">ib"',
    },
    {
      "key" => ">at",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["greaterThanat"],
      "search" => en_data["indentText"]["commands"]["greaterThanat"],
      "ascript" => 'key code 53//keystroke ">at"',
    },
    {
      "key" => "3==",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["3=="],
      "search" => en_data["indentText"]["commands"]["3=="],
      "ascript" => 'key code 53//keystroke "3=="',
    },
    {
      "key" => "=%",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["=Percent"],
      "search" => en_data["indentText"]["commands"]["=Percent"],
      "ascript" => 'key code 53//keystroke "=%"',
    },
    {
      "key" => "=iB",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["iB"],
      "search" => en_data["indentText"]["commands"]["iB"],
      "ascript" => 'key code 53//keystroke "iB"',
    },
    {
      "key" => "gg=G",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["gg=G"],
      "search" => en_data["indentText"]["commands"]["gg=G"],
      "ascript" => 'key code 53//keystroke "gg=G"',
    },
    {
      "key" => "]p",
      "catcode"=> "indentText",
      "category"=> data["indentText"]["title"],
      "desc" => data["indentText"]["commands"]["closeSquarep"],
      "search" => en_data["indentText"]["commands"]["closeSquarep"],
      "ascript" => 'key code 53//keystroke "]p"',
    },
    # 'exiting
    {
      "key" => ":w",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonw"],
      "search" => en_data["exiting"]["commands"]["colonw"],
      "ascript" => 'key code 53//keystroke ":w" & return',
    },
    {
      "key" => ":w !sudo tee %",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonwsudo"],
      "search" => en_data["exiting"]["commands"]["colonwsudo"],
      "ascript" => 'key code 53//keystroke ":w !sudo tee %"',
    },
    {
      "key" => ":wq or :x or ZZ",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonwq"],
      "search" => en_data["exiting"]["commands"]["colonwq"],
      "ascript" => 'key code 53//keystroke ":wq" & return',
    },
    {
      "key" => ":q",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonq"],
      "search" => en_data["exiting"]["commands"]["colonq"],
      "ascript" => 'key code 53//keystroke ":q" & return',
    },
    {
      "key" => ":q! or ZQ",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonqbang"],
      "search" => en_data["exiting"]["commands"]["colonqbang"],
      "ascript" => 'key code 53//keystroke ":q!" & return',
    },
    {
      "key" => ":wqa",
      "catcode"=> "exiting",
      "category"=> data["exiting"]["title"],
      "desc" => data["exiting"]["commands"]["colonwqa"],
      "search" => en_data["exiting"]["commands"]["colonwqa"],
      "ascript" => 'key code 53//keystroke ":wqa" & return',
    },
    #'searchAndReplace
    {
      "key" => "/pattern",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["forwardSlashPattern"],
      "search" => en_data["searchAndReplace"]["commands"]["forwardSlashPattern"],
      "ascript" => 'key code 53//keystroke "/pattern"',
    },
    {
      "key" => "?pattern",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["questionMarkPattern"],
      "search" => en_data["searchAndReplace"]["commands"]["questionMarkPattern"],
      "ascript" => 'key code 53//keystroke "?pattern"',
    },
    {
      "key" => "\\vpattern",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["backslashVpattern"],
      "search" => en_data["searchAndReplace"]["commands"]["backslashVpattern"],
      "ascript" => 'key code 53//keystroke "\\\\vpattern"',
    },
    {
      "key" => "n",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["n"],
      "search" => en_data["searchAndReplace"]["commands"]["n"],
      "ascript" => 'key code 53//keystroke "n"',
    },
    {
      "key" => "N",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["N"],
      "search" => en_data["searchAndReplace"]["commands"]["N"],
      "ascript" => 'key code 53//keystroke "N"',
    },
    {
      "key" => ":%s/old/new/g",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashg"],
      "search" => en_data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashg"],
      "ascript" => 'key code 53//keystroke ":%s/old/new/g"',
    },
    {
      "key" => ":%s/old/new/gc",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashgc"],
      "search" => en_data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashgc"],
      "ascript" => 'key code 53//keystroke ":%s/old/new/gc"',
    },
    {
      "key" => ":noh[lsearch]",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["colonnoh"],
      "search" => en_data["searchAndReplace"]["commands"]["colonnoh"],
      "ascript" => 'key code 53//keystroke ":noh[lsearch]"',
    },
    {
      "key" => "*",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["asterisk"],
      "search" => en_data["searchAndReplace"]["commands"]["asterisk"],
      "ascript" => 'key code 53//keystroke "*"',
    },
    {
      "key" => "#",
      "catcode"=> "searchAndReplace",
      "category"=> data["searchAndReplace"]["title"],
      "desc" => data["searchAndReplace"]["commands"]["hash"],
      "search" => en_data["searchAndReplace"]["commands"]["hash"],
      "ascript" => 'key code 53//keystroke "#"',
    },
    # 'searchMultipleFiles
    {
      "key" => ":vim[grep] /pattern/ file",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["colonvimgrep"],
      "search" => en_data["searchMultipleFiles"]["commands"]["colonvimgrep"],
      "ascript" => 'key code 53//keystroke ":vim[grep]"//key code 49//keystroke "/pattern/"//key code 49//keystroke "file"',
    },
    {
      "key" => ":cn[ext]",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["coloncn"],
      "search" => en_data["searchMultipleFiles"]["commands"]["coloncn"],
      "ascript" => 'key code 53//keystroke ":cn" & return',
    },
    {
      "key" => ":cp[revious]",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["coloncp"],
      "search" => en_data["searchMultipleFiles"]["commands"]["coloncp"],
      "ascript" => 'key code 53//keystroke ":cp" & return',
    },
    {
      "key" => ":cope[n]",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["coloncopen"],
      "search" => en_data["searchMultipleFiles"]["commands"]["coloncopen"],
      "ascript" => 'key code 53//keystroke ":cope" & return',
    },
    {
      "key" => ":ccl[ose]",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["coloncclose"],
      "search" => en_data["searchMultipleFiles"]["commands"]["coloncclose"],
      "ascript" => 'key code 53//keystroke ":ccl" & return',
    },
    {
      "key" => "colonWa",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["colonWa"],
      "search" => en_data["searchMultipleFiles"]["commands"]["colonWa"],
      "ascript" => 'key code 53//keystroke ":wa" & return',
    },
    {
      "key" => ":ccl[ose]",
      "catcode"=> "searchMultipleFiles",
      "category"=> data["searchMultipleFiles"]["title"],
      "desc" => data["searchMultipleFiles"]["commands"]["coloncclose"],
      "search" => en_data["searchMultipleFiles"]["commands"]["coloncclose"],
      "ascript" => 'key code 53//keystroke ":ccl" & return',
    },
    #'tabs
    {
      "key" => ":tabnew or :tabnew file",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["colonTabNew"],
      "search" => en_data["tabs"]["commands"]["colonTabNew"],
      "ascript" => 'key code 53//keystroke ":tabnew"//key code 49//keystroke "file" & return',
    },
    {
      "key" => "Ctrl+wT",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["ctrlPluswT"],
      "search" => en_data["tabs"]["commands"]["ctrlPluswT"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "T"',
    },
    {
      "key" => "gt or :tabn[ext]",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["gt"],
      "search" => en_data["tabs"]["commands"]["gt"],
      "ascript" => 'key code 53//keystroke "gt"',
    },
    {
      "key" => "gT or :tabp[revious]",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["gT"],
      "search" => en_data["tabs"]["commands"]["gT"],
      "ascript" => 'key code 53//keystroke "gT"',
    },
    {
      "key" => "#gt",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["hashgt"],
      "search" => en_data["tabs"]["commands"]["hashgt"],
      "ascript" => 'key code 53//keystroke "#gt"',
    },
    {
      "key" => ":tabm[ove]",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["colontabmove"],
      "search" => en_data["tabs"]["commands"]["colontabmove"],
      "ascript" => 'key code 53//keystroke ":tabm" & return',
    },
    {
      "key" => ":tabc[lose]",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["colontabc"],
      "search" => en_data["tabs"]["commands"]["colontabc"],
      "ascript" => 'key code 53//keystroke ":tabc" & return',
    },
    {
      "key" => ":tabo[nly]",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["colontabo"],
      "search" => en_data["tabs"]["commands"]["colontabo"],
      "ascript" => 'key code 53//keystroke ":tabo" & return',
    },
    {
      "key" => ":tabdo command",
      "catcode"=> "tabs",
      "category"=> data["tabs"]["title"],
      "desc" => data["tabs"]["commands"]["colontabdo"],
      "search" => en_data["tabs"]["commands"]["colontabdo"],
      "ascript" => 'key code 53//keystroke ":tabdo"//key code 49//keystroke "command"',
    },
    # 'workingWithMultipleFiles
    {
      "key" => ":e[dit] file",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colone"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colone"],
      "ascript" => 'key code 53//keystroke ":e"//key code 49//keystroke "file"',
    },
    {
      "key" => ":bn[ext]",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonbnext"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonbnext"],
      "ascript" => 'key code 53//keystroke ":bn" & return',
    },
    {
      "key" => ":bp[revious]",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonbprev"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonbprev"],
      "ascript" => 'key code 53//keystroke ":bp" & return',
    },
    {
      "key" => ":bd[elete]",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonbd"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonbd"],
      "ascript" => 'key code 53//keystroke ":bd" & return',
    },
    {
      "key" => ":b[uffer]#",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonbnumber"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonbnumber"],
      "ascript" => 'key code 53//keystroke ":b#"',
    },
    {
      "key" => ":b[uffer] file",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonbfile"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonbfile"],
      "ascript" => 'key code 53//keystroke ":b"//key code 49//keystroke "file"',
    },
    {
      "key" => ":ls or :buffers",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonls"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonls"],
      "ascript" => 'key code 53//keystroke ":ls" & return',
    },
    {
      "key" => ":sp[lit] file",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonsp"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonsp"],
      "ascript" => 'key code 53//keystroke ":sp"//key code 49//keystroke "file"',
    },
    {
      "key" => ":vs[plit] file",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonvsp"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonvsp"],
      "ascript" => 'key code 53//keystroke ":vs"//key code 49//keystroke "file"',
    },
    {
      "key" => ":vert[ical] ba[ll]",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colonvertba"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colonvertba"],
      "ascript" => 'key code 53//keystroke ":vert"//key code 49//keystroke "ba" & return',
    },
    {
      "key" => ":tab ba[ll]",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["colontabba"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["colontabba"],
      "ascript" => 'key code 53//keystroke ":tab"//key code 49//keystroke "ba" & return',
    },
    {
      "key" => "Ctrl+w s",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusws"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPlusws"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "s"',
    },
    {
      "key" => "Ctrl+w v",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswv"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswv"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "v"',
    },
    {
      "key" => "Ctrl+w w",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusww"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPlusww"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "w"',
    },
    {
      "key" => "Ctrl+w q",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswq"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswq"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "q"',
    },
    {
      "key" => "Ctrl+w x",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswx"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswx"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "x"',
    },
    {
      "key" => "Ctrl+w =",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusw="],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPlusw="],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "="',
    },
    {
      "key" => "Ctrl+w h",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswh"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswh"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "h"',
    },
    {
      "key" => "Ctrl+w l",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswl"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswl"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "l"',
    },
    {
      "key" => "Ctrl+w j",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswj"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswj"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "j"',
    },
    {
      "key" => "Ctrl+w k",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswk"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswk"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "k"',
    },
    {
      "key" => "Ctrl+w H",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswH"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswH"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "H"',
    },
    {
      "key" => "Ctrl+w L",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswL"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswL"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "L"',
    },
    {
      "key" => "Ctrl+w J",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswJ"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswJ"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "J"',
    },
    {
      "key" => "Ctrl+w K",
      "catcode"=> "workingWithMultipleFiles",
      "category"=> data["workingWithMultipleFiles"]["title"],
      "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswK"],
      "search" => en_data["workingWithMultipleFiles"]["commands"]["ctrlPluswK"],
      "ascript" => 'key code 53//keystroke "w" using control down//keystroke "K"',
    },
    # 'diff
    {
      "key" => "zf",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zf"],
      "search" => en_data["diff"]["commands"]["zf"],
      "ascript" => 'key code 53//keystroke "zf"',
    },
    {
      "key" => "zd",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zd"],
      "search" => en_data["diff"]["commands"]["zd"],
      "ascript" => 'key code 53//keystroke "zd"',
    },
    {
      "key" => "za",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["za"],
      "search" => en_data["diff"]["commands"]["za"],
      "ascript" => 'key code 53//keystroke "za"',
    },
    {
      "key" => "zo",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zo"],
      "search" => en_data["diff"]["commands"]["zo"],
      "ascript" => 'key code 53//keystroke "zo"',
    },
    {
      "key" => "zc",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zc"],
      "search" => en_data["diff"]["commands"]["zc"],
      "ascript" => 'key code 53//keystroke "zc"',
    },
    {
      "key" => "zr",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zr"],
      "search" => en_data["diff"]["commands"]["zr"],
      "ascript" => 'key code 53//keystroke "zr"',
    },
    {
      "key" => "zm",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zm"],
      "search" => en_data["diff"]["commands"]["zm"],
      "ascript" => 'key code 53//keystroke "zm"',
    },
    {
      "key" => "zi",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["zi"],
      "search" => en_data["diff"]["commands"]["zi"],
      "ascript" => 'key code 53//keystroke "zi"',
    },
    {
      "key" => "]c",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["closeSquarec"],
      "search" => en_data["diff"]["commands"]["closeSquarec"],
      "ascript" => 'key code 53//keystroke "]c"',
    },
    {
      "key" => "[c",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["openSquarec"],
      "search" => en_data["diff"]["commands"]["openSquarec"],
      "ascript" => 'key code 53//keystroke "[c"',
    },
    {
      "key" => "do or :diffg[et]",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["do"],
      "search" => en_data["diff"]["commands"]["do"],
      "ascript" => 'key code 53//keystroke "do"',
    },
    {
      "key" => "dp or :diffpu[t]",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["dp"],
      "search" => en_data["diff"]["commands"]["dp"],
      "ascript" => 'key code 53//keystroke "dp"',
    },
    {
      "key" => ":diffthis",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["colonDiffthis"],
      "search" => en_data["diff"]["commands"]["colonDiffthis"],
      "ascript" => 'key code 53//keystroke ":diffthis" & return',
    },
    {
      "key" => ":dif[fupdate]",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["colonDiffupdate"],
      "search" => en_data["diff"]["commands"]["colonDiffupdate"],
      "ascript" => 'key code 53//keystroke ":dif" & return',
    },
    {
      "key" => ":diffo[ff]",
      "catcode"=> "diff",
      "category"=> data["diff"]["title"],
      "desc" => data["diff"]["commands"]["colonDiffoff"],
      "search" => en_data["diff"]["commands"]["colonDiffoff"],
      "ascript" => 'key code 53//keystroke ":diffo" & return',
    },
    # spell
    {
      "key" => ":set spell spelllang=en_us",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["setSpellEnUs"],
      "search" => en_data["spell"]["commands"]["setSpellEnUs"],
      "ascript" => 'key code 53//keystroke ":set"//key code 49//keystroke "spell"//key code 49//keystroke "spelllang=en_us" & return',
    },
    {
      "key" => ":set nospell",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["setNoSpell"],
      "search" => en_data["spell"]["commands"]["setNoSpell"],
      "ascript" => 'key code 53//keystroke ":set"//key code 49//keystroke "nospell" & return',
    },
    {
      "key" => "]s",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["closeBrackets"],
      "search" => en_data["spell"]["commands"]["closeBrackets"],
      "ascript" => 'key code 53//keystroke "]s"',
    },
    {
      "key" => "[s",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["openBrackets"],
      "search" => en_data["spell"]["commands"]["openBrackets"],
      "ascript" => 'key code 53//keystroke "[s"',
    },
    {
      "key" => "z=",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["z="],
      "search" => en_data["spell"]["commands"]["z="],
      "ascript" => 'key code 53//keystroke "z="',
    },
    {
      "key" => "zg",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["zg"],
      "search" => en_data["spell"]["commands"]["zg"],
      "ascript" => 'key code 53//keystroke "zg"',
    },
    {
      "key" => "zw",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["zw"],
      "search" => en_data["spell"]["commands"]["zw"],
      "ascript" => 'key code 53//keystroke "zw"',
    },
    {
      "key" => "zu",
      "catcode"=> "spell",
      "category"=> data["spell"]["title"],
      "desc" => data["spell"]["commands"]["zu"],
      "search" => en_data["spell"]["commands"]["zu"],
      "ascript" => 'key code 53//keystroke "zu"',
    },
    # misc
    {
      "key" => "Ctrl+a",
      "catcode"=> "misc",
      "category"=> data["misc"]["title"],
      "desc" => data["misc"]["commands"]["Ctrla"],
      "search" => en_data["misc"]["commands"]["Ctrla"],
      "ascript" => 'key code 53//keystroke "a" using control down',
    },
    {
      "key" => "Ctrl+x",
      "catcode"=> "misc",
      "category"=> data["misc"]["title"],
      "desc" => data["misc"]["commands"]["Ctrlx"],
      "search" => en_data["misc"]["commands"]["Ctrlx"],
      "ascript" => 'key code 53//keystroke "x" using control down',
    },
    {
      "key" => "gv",
      "catcode"=> "misc",
      "category"=> data["misc"]["title"],
      "desc" => data["misc"]["commands"]["gv"],
      "search" => en_data["misc"]["commands"]["gv"],
      "ascript" => 'key code 53//keystroke "gv"'
    },
    {
      "key" => "Ctrl+r =",
      "catcode"=> "misc",
      "category"=> data["misc"]["title"],
      "desc" => data["misc"]["commands"]["CtrlrEqual"],
      "search" => en_data["misc"]["commands"]["CtrlrEqual"],
      "ascript" => 'key code 53//keystroke "r" using control down//keystroke "="'
    },
    {
      "key" => "set fenc=UTF-8",
      "catcode"=> "misc",
      "category"=> data["misc"]["title"],
      "desc" => data["misc"]["commands"]["setFencUtf"],
      "search" => en_data["misc"]["commands"]["setFencUtf"],
      "ascript" => 'key code 53//keystroke "set"//key code 49//keystroke "fenc=UTF-8"'
    },
    # regex
    {
      "key" => "\\",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["backslash"],
      "search" => en_data["regex"]["commands"]["backslash"],
      "ascript" => 'keystroke "\\\\"',
    },
    {
      "key" => "^",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["hat"],
      "search" => en_data["regex"]["commands"]["hat"],
      "ascript" => 'keystroke "^"',
    },
    {
      "key" => "$",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["dollar"],
      "search" => en_data["regex"]["commands"]["dollar"],
      "ascript" => 'keystroke "$"',
    },
    {
      "key" => ".",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["dot"],
      "search" => en_data["regex"]["commands"]["dot"],
      "ascript" => 'keystroke "."',
    },
    {
      "key" => "*",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["star"],
      "search" => en_data["regex"]["commands"]["star"],
      "ascript" => 'keystroke "*"',
    },
    {
      "key" => "~",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["tilde"],
      "search" => en_data["regex"]["commands"]["tilde"],
      "ascript" => 'keystroke ""~',
    },
    {
      "key" => "[...]",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["range"],
      "search" => en_data["regex"]["commands"]["range"],
      "ascript" => 'keystroke "[...]"',
    },
    {
      "key" => "[^...]",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["notRange"],
      "search" => en_data["regex"]["commands"]["notRange"],
      "ascript" => 'keystroke "[^...]"',
    },
    {
      "key" => "&",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["ampersand"],
      "search" => en_data["regex"]["commands"]["ampersand"],
      "ascript" => 'keystroke "&"',
    },
    {
      "key" => "\\<",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["backSlashLessThan"],
      "search" => en_data["regex"]["commands"]["backSlashLessThan"],
      "ascript" => 'keystroke "\\\\<"',
    },
    {
      "key" => "\\>",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["backSlashGreaterThan"],
      "search" => en_data["regex"]["commands"]["backSlashGreaterThan"],
      "ascript" => 'keystroke "\\\\>"',
    },
    {
      "key" => "\\(...\\)",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["group"],
      "search" => en_data["regex"]["commands"]["group"],
      "ascript" => 'keystroke "\\\\(...\\\\)"',
    },
    {
      "key" => "\\|",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["separator"],
      "search" => en_data["regex"]["commands"]["separator"],
      "ascript" => 'keystroke "\\\\|"',
    },
    {
      "key" => "\\_.",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["anyChar"],
      "search" => en_data["regex"]["commands"]["anyChar"],
      "ascript" => 'keystroke "\\\\_."',
    },
    {
      "key" => "\\+",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["oneOrMore"],
      "search" => en_data["regex"]["commands"]["oneOrMore"],
      "ascript" => 'keystroke "\\\\+"',
    },
    {
      "key" => "\\=",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["backSlashEqual"],
      "search" => en_data["regex"]["commands"]["backSlashEqual"],
      "ascript" => 'keystroke "\\\\="',
    },
    {
      "key" => "\\?",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["backSlashQuestion"],
      "search" => en_data["regex"]["commands"]["backSlashQuestion"],
      "ascript" => 'keystroke "\\\\?"',
    },
    {
      "key" => "\\{n,m}",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["nToM"],
      "search" => en_data["regex"]["commands"]["nToM"],
      "ascript" => 'keystroke "\\\\{n,m}"',
    },
    {
      "key" => "\\{n}",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["nQuantifier"],
      "search" => en_data["regex"]["commands"]["nQuantifier"],
      "ascript" => 'keystroke "\\\\{n}"',
    },
    {
      "key" => "\\{n,}",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["atLeastN"],
      "search" => en_data["regex"]["commands"]["atLeastN"],
      "ascript" => 'keystroke ""\\\\{n,}',
    },
    {
      "key" => "\\{,m}",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["zeroToM"],
      "search" => en_data["regex"]["commands"]["zeroToM"],
      "ascript" => 'keystroke "\\\\{,}"',
    },
    {
      "key" => ":%g/<pa­tte­rn>/d",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["delAllLinesMatching"],
      "search" => en_data["regex"]["commands"]["delAllLinesMatching"],
      "ascript" => 'key code 53//keystroke ":%g/<pa­tte­r/d"',
    },
    {
      "key" => ":%v/<pa­tte­rn>/d",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["delAllLinesNotMatching"],
      "search" => en_data["regex"]["commands"]["delAllLinesNotMatching"],
      "ascript" => 'key code 53//keystroke ":%v/<pa­tte­r/d"',
    },
    {
      "key" => ":%s/^.*$\\n//",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["deleteEmptyLines"],
      "search" => en_data["regex"]["commands"]["deleteEmptyLines"],
      "ascript" => 'key code 53//keystroke ":%s/^.*$\\\\n//"',
    },
    {
      "key" => ":s/<pattern>/new &/",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["replacePattern"],
      "search" => en_data["regex"]["commands"]["replacePattern"],
      "ascript" => 'key code 53//keystroke ":%s/<pattern>/new &/"',
    },
    {
      "key" => ":s/<pattern>/\\=@a/",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["replacePatternByRegister"],
      "search" => en_data["regex"]["commands"]["replacePatternByRegister"],
      "ascript" => 'key code 53//keystroke ":%s/<pattern>/\\\\=@a/"',
    },
    {
      "key" => ":s/<pattern>//gn",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["countNumOccurrence"],
      "search" => en_data["regex"]["commands"]["countNumOccurrence"],
      "ascript" => 'key code 53//keystroke ":%s/<pattern>//gn"',
    },
    {
      "key" => "\\zs",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["matchStart"],
      "search" => en_data["regex"]["commands"]["matchStart"],
      "ascript" => 'keystroke "\\\\zs"',
    },
    {
      "key" => "\\ze",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["matchEnd"],
      "search" => en_data["regex"]["commands"]["matchEnd"],
      "ascript" => 'keystroke "\\\\ze"',
    },
    {
      "key" => "<atom>\\@<=<pattern>",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["positiveLookBehind"],
      "search" => en_data["regex"]["commands"]["positiveLookBehind"],
      "ascript" => 'keystroke "<atom>\\\\@<=<pattern>"',
    },
    {
      "key" => "<pattern><atom>\\@=",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["positiveLookAhead"],
      "search" => en_data["regex"]["commands"]["positiveLookAhead"],
      "ascript" => 'keystroke "<pattern><atom>\\\\@="',
    },
    {
      "key" => "<atom>\\@<!<pattern>",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["negativeLookBehind"],
      "search" => en_data["regex"]["commands"]["negativeLookBehind"],
      "ascript" => 'keystroke "<atom>\\\\@<!<pattern>"',
    },
    {
      "key" => "<pattern><atom>\\@!",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["negativeLookAhead"],
      "search" => en_data["regex"]["commands"]["negativeLookAhead"],
      "ascript" => 'keystroke "<pattern><atom>\\\\@!"',
    },
    {
      "key" => "\\{-}",
      "catcode"=> "regex",
      "category"=> data["regex"]["title"],
      "desc" => data["regex"]["commands"]["nonGreedyQuantifier"],
      "search" => en_data["regex"]["commands"]["nonGreedyQuantifier"],
      "ascript" => 'keystroke "\\\\{-}"',
    },
  ]
end
