require 'json'

class Hash
  def deep_merge(*others)
    self.clone.deep_merge!(*others)
  end

  def deep_merge!(*others)
    _child_merge = -> (_, self_val, other_val){
      if self_val.instance_of?(Hash) && other_val.instance_of?(Hash)
        self_val.merge other_val, &_child_merge
      else
        other_val
      end
    }
    self.merge! *others, &_child_merge
  end
end

locale    = ARGV[0] || "en_us"
fixed_order  = /\A(?:True|true|T|t)\z/ =~ ARGV[1] ? true : false
separator = ARGV[2] || "⎯"

fcurrent = File.dirname(__FILE__)
dcurrent = File.expand_path(fcurrent)

base_json= File.read(File.join(dcurrent, "base.json"))
base_data  = JSON.parse(base_json)

locale_json= File.read(File.join(dcurrent, "locales", "#{locale}.json"))
locale_json.gsub!(/<[^<>]+>([^<>]+)<\/[^<>]+>/){$1}
locale_json.gsub!(/\(\)/){""}
locale_json.gsub!(/\([^\(\)]+\)/){""}
locale_data  = JSON.parse(locale_json)

data = base_data.deep_merge locale_data

vim_cheatsheet = [
  # global
  {
    "key"  => ":h[elp] " + data["words"]["keyword"],
    "catcode"=> "global",
    "category"=> data["global"]["title"],
    "desc" => data["global"]["commands"]["helpForKeyword"],
    "ascript" => 'keystroke ":h"//key code 49//keystroke "keyword"',
  },
  {
    "key"  => ":sav[eas] " + data["words"]["file"],
    "catcode"=> "global",
    "category"=> data["global"]["title"],
    "desc" => data["global"]["commands"]["saveAsFile"],
    "ascript" => 'keystroke ":sav"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":clo[se]",
    "catcode"=> "global",
    "category"=> data["global"]["title"],
    "desc" => data["global"]["commands"]["closePane"],
    "ascript" => 'keystroke ":clo" & return',
  },
  {
    "key"  => ":ter[minal]",
    "catcode"=> "global",
    "category"=> data["global"]["title"],
    "desc" => data["global"]["commands"]["colonTerminal"],
    "ascript" => 'keystroke ":ter" & return',
  },
  {
    "key"  => "K",
    "catcode"=> "global",
    "category"=> data["global"]["title"],
    "desc" => data["global"]["commands"]["K"],
    "ascript" => 'keystroke "K"',
  },
  #cursorMovement
  {
    "key"  => "h",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["h"],
    "ascript" => 'keystroke "h"',
  },
  {
    "key"  => "j",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["j"],
    "ascript" => 'keystroke "j"',
  },
  {
    "key"  => "k",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["k"],
    "ascript" => 'keystroke "k"',
  },
  {
    "key"  => "l",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["l"],
    "ascript" => 'keystroke "l"',
  },
  {
    "key"  => "gj",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gj"],
    "ascript" => 'keystroke "gj"',
  },
  {
    "key"  => "gk",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gk"],
    "ascript" => 'keystroke "gk"',
  },
  {
    "key"  => "H",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["H"],
    "ascript" => 'keystroke "H"',
  },
  {
    "key"  => "M",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["M"],
    "ascript" => 'keystroke "M"',
  },
  {
    "key"  => "L",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["L"],
    "ascript" => 'keystroke "L"',
  },
  {
    "key"  => "w",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["w"],
    "ascript" => 'keystroke "w"',
  },
  {
    "key"  => "W",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["W"],
    "ascript" => 'keystroke "W"',
  },
  {
    "key"  => "e",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["e"],
    "ascript" => 'keystroke "e"',
  },
  {
    "key"  => "E",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["E"],
    "ascript" => 'keystroke "E"',
  },
  {
    "key"  => "b",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["b"],
    "ascript" => 'keystroke "b"',
  },
  {
    "key"  => "B",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["B"],
    "ascript" => 'keystroke "B"',
  },
  {
    "key"  => "ge",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["ge"],
    "ascript" => 'keystroke "ge"',
  },
  {
    "key"  => "gE",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gE"],
    "ascript" => 'keystroke "gE"',
  },
  {
    "key"  => "%",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["percent"],
    "ascript" => 'keystroke "%"',
  },
  {
    "key"  => "0",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["zero"],
    "ascript" => 'keystroke "0"',
  },
  {
    "key"  => "^",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["caret"],
    "ascript" => 'keystroke "^"',
  },
  {
    "key"  => "$",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["dollar"],
    "ascript" => 'keystroke "$"',
  },
  {
    "key"  => "g_",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["g_"],
    "ascript" => 'keystroke "g_"',
  },
  {
    "key"  => "gg",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gg"],
    "ascript" => 'keystroke "gg"',
  },
  {
    "key"  => "G",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["G"],
    "ascript" => 'keystroke "G"',
  },
  {
    "key"  => "5gg or 5G",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["fiveG"],
    "ascript" => 'keystroke "5gg"',
  },
  {
    "key"  => "gd",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gd"],
    "ascript" => 'keystroke "gd"',
  },
  {
    "key"  => "gD",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["gD"],
    "ascript" => 'keystroke "gD"',
  },
  {
    "key"  => "fx",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["fx"],
    "ascript" => 'keystroke "fx"',
  },
  {
    "key"  => "tx",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["tx"],
    "ascript" => 'keystroke "tx"',
  },
  {
    "key"  => "Fx",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["Fx"],
    "ascript" => 'keystroke "Fx"',
  },
  {
    "key"  => "Tx",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["Tx"],
    "ascript" => 'keystroke "Tx"',
  },
  {
    "key"  => ";",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["semicolon"],
    "ascript" => 'keystroke ";"',
  },
  {
    "key"  => ",",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["comma"],
    "ascript" => 'keystroke ","',
  },
  {
    "key"  => "}",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["closeCurlyBrace"],
    "ascript" => 'keystroke "}"',
  },
  {
    "key"  => "{",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["openCurlyBrace"],
    "ascript" => 'keystroke "{"',
  },
  {
    "key"  => "zz",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["centerCursor"],
    "ascript" => 'keystroke "zz"',
  },
  {
    "key"  => "Ctrl+e",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPluse"],
    "ascript" => 'keystroke "e" using control down',
  },
  {
    "key"  => "Ctrl+y",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPlusy"],
    "ascript" => 'keystroke "y" using control down',
  },
  {
    "key"  => "Ctrl+b",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPlusb"],
    "ascript" => 'keystroke "b" using control down',
  },
  {
    "key"  => "Ctrl+f",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPlusf"],
    "ascript" => 'keystroke "f" using control down',
  },
  {
    "key"  => "Ctrl+u",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPlusu"],
    "ascript" => 'keystroke "u" using control down',
  },
  {
    "key"  => "Ctrl+d",
    "catcode"=> "cursorMovement",
    "category"=> data["cursorMovement"]["title"],
    "desc" => data["cursorMovement"]["commands"]["CtrlPlusd"],
    "ascript" => 'keystroke "d" using control down',
  },
  # 'insertMode.title'
  {
    "key"  => "i",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["i"],
    "ascript" => 'keystroke "i"',
  },
  {
    "key"  => "I",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["I"],
    "ascript" => 'keystroke "I"',
  },
  {
    "key"  => "a",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["a"],
    "ascript" => 'keystroke "a"',
  },
  {
    "key"  => "A",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["A"],
    "ascript" => 'keystroke "A"',
  },
  {
    "key"  => "o",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["o"],
    "ascript" => 'keystroke "o"',
  },
  {
    "key"  => "O",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["O"],
    "ascript" => 'keystroke "O"',
  },
  {
    "key"  => "ea",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ea"],
    "ascript" => 'keystroke "ea"',
  },
  {
    "key"  => "Ctrl+h",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlush"],
    "ascript" => 'keystroke "h" using control down',
  },
  {
    "key"  => "Ctrl+w",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusw"],
    "ascript" => 'keystroke "w" using control down',
  },
  {
    "key"  => "Ctrl+j",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusj"],
    "ascript" => 'keystroke "j" using control down',
  },
  {
    "key"  => "Ctrl+t",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlust"],
    "ascript" => 'keystroke "t" using control down',
  },
  {
    "key"  => "Ctrl+t",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlust"],
    "ascript" => 'keystroke "t" using control down',
  },
  {
    "key"  => "Ctrl+d",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusd"],
    "ascript" => 'keystroke "d" using control down',
  },
  {
    "key"  => "Ctrl+n",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusn"],
    "ascript" => 'keystroke "n" using control down',
  },
  {
    "key"  => "Ctrl+p",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusp"],
    "ascript" => 'keystroke "p" using control down',
  },
  {
    "key"  => "Ctrl+r x",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusrx"],
    "ascript" => 'keystroke "r" using control down//keystroke "x"',
  },
  {
    "key"  => "Ctrl+o x",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["ctrlPlusox"],
    "ascript" => 'keystroke "o" using control down//keystroke "x"',
  },
  {
    "key"  => "Esc",
    "catcode"=> "insertMode",
    "category"=> data["insertMode"]["title"],
    "desc" => data["insertMode"]["commands"]["Esc"],
    "ascript" => 'key code 53',
  },
  # 'editing.title'
  {
    "key"  => "r",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["r"],
    "ascript" => 'keystroke "r"',
  },
  {
    "key"  => "R",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["R"],
    "ascript" => 'keystroke "R"',
  },
  {
    "key"  => "J",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["J"],
    "ascript" => 'keystroke "J"',
  },
  {
    "key"  => "gJ",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["gJ"],
    "ascript" => 'keystroke "gJ"',
  },
  {
    "key"  => "gwip",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["gwip"],
    "ascript" => 'keystroke "gwip"',
  },
  {
    "key"  => "g~",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["gTilde"],
    "ascript" => 'keystroke "g~"',
  },
  {
    "key"  => "gu",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["gu"],
    "ascript" => 'keystroke "gu"',
  },
  {
    "key"  => "gU",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["gU"],
    "ascript" => 'keystroke "gU"',
  },
  {
    "key"  => "cc",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["cc"],
    "ascript" => 'keystroke "cc"',
  },
  {
    "key"  => "c$ or C",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["cDollar"],
    "ascript" => 'keystroke "g$"',
  },
  {
    "key"  => "ciw",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["ciw"],
    "ascript" => 'keystroke "ciw"',
  },
  {
    "key"  => "cw or ce",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["cw"],
    "ascript" => 'keystroke "cw"',
  },
  {
    "key"  => "s",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["s"],
    "ascript" => 'keystroke "s"',
  },
  {
    "key"  => "S",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["S"],
    "ascript" => 'keystroke "S"',
  },
  {
    "key"  => "xp",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["xp"],
    "ascript" => 'keystroke "xp"',
  },
  {
    "key"  => "u",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["u"],
    "ascript" => 'keystroke "u"',
  },
  {
    "key"  => "U",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["U"],
    "ascript" => 'keystroke "U"',
  },
  {
    "key"  => "Ctrl+r",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["CtrlPlusr"],
    "ascript" => 'keystroke "r" using control down',
  },
  {
    "key"  => ".",
    "catcode"=> "editing",
    "category"=> data["editing"]["title"],
    "desc" => data["editing"]["commands"]["dot"],
    "ascript" => 'keystroke "."',
  },
  # 'markingText.title'
  {
    "key"  => "v",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["v"],
    "ascript" => 'keystroke "v"',
  },
  {
    "key"  => "V",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["V"],
    "ascript" => 'keystroke "V"',
  },
  {
    "key"  => "o",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["o"],
    "ascript" => 'keystroke "o"',
  },
  {
    "key"  => "Ctrl+v",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["CtrlPlusv"],
    "ascript" => 'keystroke "v" using control down',
  },
  {
    "key"  => "O",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["O"],
    "ascript" => 'keystroke "O"',
  },
  {
    "key"  => "aw",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["aw"],
    "ascript" => 'keystroke "aw"',
  },
  {
    "key"  => "ab",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["ab"],
    "ascript" => 'keystroke "ab"',
  },
  {
    "key"  => "aB",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["aB"],
    "ascript" => 'keystroke "aB"',
  },
  {
    "key"  => "at",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["at"],
    "ascript" => 'keystroke "at"',
  },
  {
    "key"  => "ib",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["ib"],
    "ascript" => 'keystroke "ib"',
  },
  {
    "key"  => "iB",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["iB"],
    "ascript" => 'keystroke "iB"',
  },
  {
    "key"  => "it",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["it"],
    "ascript" => 'keystroke "it"',
  },
  {
    "key"  => "Esc",
    "catcode"=> "markingText",
    "category"=> data["markingText"]["title"],
    "desc" => data["markingText"]["commands"]["Esc"],
    "ascript" => 'key code 53',
  },
  # 'visualCommands.title'
  {
    "key"  => ">",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["greaterThan"],
    "ascript" => 'keystroke ">"',
  },
  {
    "key"  => "<",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["lessThan"],
    "ascript" => 'keystroke "<"',
  },
  {
    "key"  => "y",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["y"],
    "ascript" => 'keystroke "y"',
  },
  {
    "key"  => "d",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["d"],
    "ascript" => 'keystroke "d"',
  },
  {
    "key"  => "~",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["tilde"],
    "ascript" => 'keystroke "~"',
  },
  {
    "key"  => "u",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["u"],
    "ascript" => 'keystroke "u"',
  },
  {
    "key"  => "U",
    "catcode"=> "visualCommands",
    "category"=> data["visualCommands"]["title"],
    "desc" => data["visualCommands"]["commands"]["U"],
    "ascript" => 'keystroke "U"',
  },
  # 'registers.title'
  {
    "key"  => ":reg[isters]",
    "catcode"=> "registers",
    "category"=> data["registers"]["title"],
    "desc" => data["registers"]["commands"]["show"],
    "ascript" => 'keystroke ":reg" & return',
  },
  {
    "key"  => "xy",
    "catcode"=> "registers",
    "category"=> data["registers"]["title"],
    "desc" => data["registers"]["commands"]["yankIntoRegisterX"],
    "ascript" => 'keystroke "xy"',
  },
  {
    "key"  => "xp",
    "catcode"=> "registers",
    "category"=> data["registers"]["title"],
    "desc" => data["registers"]["commands"]["pasteRegisterX"],
    "ascript" => 'keystroke "xp"',
  },
  {
    "key"  => "+y",
    "catcode"=> "registers",
    "category"=> data["registers"]["title"],
    "desc" => data["registers"]["commands"]["quotePlusy"],
    "ascript" => 'keystroke "+y"',
  },
  {
    "key"  => "+p",
    "catcode"=> "registers",
    "category"=> data["registers"]["title"],
    "desc" => data["registers"]["commands"]["quotePlusp"],
    "ascript" => 'keystroke "+p"',
  },
  # 'marks.title'
  {
    "key"  => "ma",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["currentPositionA"],
    "ascript" => 'keystroke "ma"',
  },
  {
    "key"  => "`a",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["jumpPositionA"],
    "ascript" => 'keystroke "`a"',
  },
  {
    "key"  => "y`a",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["yankToMarkA"],
    "ascript" => 'keystroke "y`a"',
  },
  {
    "key"  => "`0",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["backtick0"],
    "ascript" => 'keystroke "`0"',
  },
  {
    "key"  => '`"',
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["backtickQuote"],
    "ascript" => 'keystroke "`\""',
  },
  {
    "key"  => "`.",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["backtickDot"],
    "ascript" => 'keystroke "`."',
  },
  {
    "key"  => "``",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["backtickBacktick"],
    "ascript" => 'keystroke "``"',
  },
  {
    "key"  => ":ju[mps]",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["colonjumps"],
    "ascript" => 'keystroke ":ju" & return',
  },
  {
    "key"  => "Ctrl+i",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["ctrlPlusi"],
    "ascript" => 'keystroke "i" using control down',
  },
  {
    "key"  => "Ctrl+o",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["ctrlPluso"],
    "ascript" => 'keystroke "o" using control down',
  },
  {
    "key"  => ":changes",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["colonchanges"],
    "ascript" => 'keystroke ":changes" & return',
  },
  {
    "key"  => "g,",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["gcomma"],
    "ascript" => 'keystroke "g,"',
  },
  {
    "key"  => "g;",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["gsemicolon"],
    "ascript" => 'keystroke "g;"',
  },
  {
    "key"  => "Ctrl+]",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["ctrlPlusCloseSquare"],
    "ascript" => 'keystroke "]" using control down',
  },
  {
    "key"  => "gf",
    "catcode"=> "marks",
    "category"=> data["marks"]["title"],
    "desc" => data["marks"]["commands"]["gf"],
    "ascript" => 'keystroke "gf"',
  },
  # 'macros.title'
  {
    "key"  => "qa",
    "catcode"=> "macros",
    "category"=> data["macros"]["title"],
    "desc" => data["macros"]["commands"]["recordA"],
    "ascript" => 'keystroke "qa"',
  },
  {
    "key"  => "q",
    "catcode"=> "macros",
    "category"=> data["macros"]["title"],
    "desc" => data["macros"]["commands"]["stopRecording"],
    "ascript" => 'keystroke "q"',
  },
  {
    "key"  => "@a",
    "catcode"=> "macros",
    "category"=> data["macros"]["title"],
    "desc" => data["macros"]["commands"]["runA"],
    "ascript" => 'keystroke "@a"',
  },
  {
    "key"  => "@@",
    "catcode"=> "macros",
    "category"=> data["macros"]["title"],
    "desc" => data["macros"]["commands"]["rerun"],
    "ascript" => 'keystroke "@@"',
  },

  # 'cutAndPaste.title'
  {
    "key"  => "yy",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["yy"],
    "ascript" => 'keystroke "yy"',
  },
  {
    "key"  => "2yy",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["twoyy"],
    "ascript" => 'keystroke "2yy"',
  },
  {
    "key"  => "yw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["yw"],
    "ascript" => 'keystroke "yw"',
  },
  {
    "key"  => "yiw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["yiw"],
    "ascript" => 'keystroke "yiw"',
  },
  {
    "key"  => "yaw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["yaw"],
    "ascript" => 'keystroke "yaw"',
  },
  {
    "key"  => "y$",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["yDollar"],
    "ascript" => 'keystroke "y$"',
  },
  {
    "key"  => "p",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["p"],
    "ascript" => 'keystroke "p"',
  },
  {
    "key"  => "P",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["P"],
    "ascript" => 'keystroke "P"',
  },
  {
    "key"  => "gp",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["gp"],
    "ascript" => 'keystroke "gp"',
  },
  {
    "key"  => "gP",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["gP"],
    "ascript" => 'keystroke "gP"',
  },
  {
    "key"  => "dd",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["dd"],
    "ascript" => 'keystroke "dd"',
  },
  {
    "key"  => "2dd",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["twodd"],
    "ascript" => 'keystroke "2dd"',
  },
  {
    "key"  => "dw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["dw"],
    "ascript" => 'keystroke "dw"',
  },
  {
    "key"  => "diw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["diw"],
    "ascript" => 'keystroke "diw"',
  },
  {
    "key"  => "daw",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["daw"],
    "ascript" => 'keystroke "daw"',
  },
  {
    "key"  => "d$ or D",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["dDollar"],
    "ascript" => 'keystroke "d$"',
  },
  {
    "key"  => "x",
    "catcode"=> "cutAndPaste",
    "category"=> data["cutAndPaste"]["title"],
    "desc" => data["cutAndPaste"]["commands"]["x"],
    "ascript" => 'keystroke "x"',
  },
  # 'indentText.title'
  {
    "key"  => ">>",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["greaterThanGreaterThan"],
    "ascript" => 'keystroke ">>"',
  },
  {
    "key"  => "<<",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["lessThanLessThan"],
    "ascript" => 'keystroke "<<"',
  },
  {
    "key"  => ">%",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["greaterThanPercent"],
    "ascript" => 'keystroke ">%"',
  },
  {
    "key"  => ">ib",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["greaterThanib"],
    "ascript" => 'keystroke ">ib"',
  },
  {
    "key"  => ">at",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["greaterThanat"],
    "ascript" => 'keystroke ">at"',
  },
  {
    "key"  => "3==",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["3=="],
    "ascript" => 'keystroke "3=="',
  },
  {
    "key"  => "=%",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["=Percent"],
    "ascript" => 'keystroke "=%"',
  },
  {
    "key"  => "=iB",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["iB"],
    "ascript" => 'keystroke "iB"',
  },
  {
    "key"  => "gg=G",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["gg=G"],
    "ascript" => 'keystroke "gg=G"',
  },
  {
    "key"  => "]p",
    "catcode"=> "indentText",
    "category"=> data["indentText"]["title"],
    "desc" => data["indentText"]["commands"]["closeSquarep"],
    "ascript" => 'keystroke "]p"',
  },
  # 'exiting.title'
  {
    "key"  => ":w",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonw"],
    "ascript" => 'keystroke ":w" & return',
  },
  {
    "key"  => ":w !sudo tee %",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonwsudo"],
    "ascript" => 'keystroke ":w !sudo tee %"',
  },
  {
    "key"  => ":wq or :x or ZZ",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonwq"],
    "ascript" => 'keystroke ":wq" & return',
  },
  {
    "key"  => ":q",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonq"],
    "ascript" => 'keystroke ":q" & return',
  },
  {
    "key"  => ":q! or ZQ",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonqbang"],
    "ascript" => 'keystroke ":q!" & return',
  },
  {
    "key"  => ":wqa",
    "catcode"=> "exiting",
    "category"=> data["exiting"]["title"],
    "desc" => data["exiting"]["commands"]["colonwqa"],
    "ascript" => 'keystroke ":wqa" & return',
  },
  #'searchAndReplace.title'
  {
    "key"  => "/pattern",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["forwardSlashPattern"],
    "ascript" => 'keystroke "/pattern"',
  },
  {
    "key"  => "?pattern",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["questionMarkPattern"],
    "ascript" => 'keystroke "?pattern"',
  },
  {
    "key"  => "\\vpattern",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["backslashVpattern"],
    "ascript" => 'keystroke "\vpattern"',
  },
  {
    "key"  => "n",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["n"],
    "ascript" => 'keystroke "n"',
  },
  {
    "key"  => "N",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["N"],
    "ascript" => 'keystroke "N"',
  },
  {
    "key"  => ":%s/old/new/g",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashg"],
    "ascript" => 'keystroke ":%s/old/new/g"',
  },
  {
    "key"  => ":%s/old/new/gc",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["colonPercentForwardSlashOldForwardSlashNewForwardSlashgc"],
    "ascript" => 'keystroke ":%s/old/new/gc"',
  },
  {
    "key"  => ":noh[lsearch]",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["colonnoh"],
    "ascript" => 'keystroke ":noh[lsearch]"',
  },
  {
    "key"  => "*",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["asterisk"],
    "ascript" => 'keystroke "*"',
  },
  {
    "key"  => "#",
    "catcode"=> "searchAndReplace",
    "category"=> data["searchAndReplace"]["title"],
    "desc" => data["searchAndReplace"]["commands"]["hash"],
    "ascript" => 'keystroke "#"',
  },
  # 'searchMultipleFiles.title'
  {
    "key"  => ":vim[grep] /pattern/ file",
    "catcode"=> "searchMultipleFiles",
    "category"=> data["searchMultipleFiles"]["title"],
    "desc" => data["searchMultipleFiles"]["commands"]["colonvimgrep"],
    "ascript" => 'keystroke ":vim[grep]"//key code 49//keystroke "/pattern/"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":cn[ext]",
    "catcode"=> "searchMultipleFiles",
    "category"=> data["searchMultipleFiles"]["title"],
    "desc" => data["searchMultipleFiles"]["commands"]["coloncn"],
    "ascript" => 'keystroke ":cn" & return',
  },
  {
    "key"  => ":cp[revious]",
    "catcode"=> "searchMultipleFiles",
    "category"=> data["searchMultipleFiles"]["title"],
    "desc" => data["searchMultipleFiles"]["commands"]["coloncp"],
    "ascript" => 'keystroke ":cp" & return',
  },
  {
    "key"  => ":cope[n]",
    "catcode"=> "searchMultipleFiles",
    "category"=> data["searchMultipleFiles"]["title"],
    "desc" => data["searchMultipleFiles"]["commands"]["coloncopen"],
    "ascript" => 'keystroke ":cope" & return',
  },
  {
    "key"  => ":ccl[ose]",
    "catcode"=> "searchMultipleFiles",
    "category"=> data["searchMultipleFiles"]["title"],
    "desc" => data["searchMultipleFiles"]["commands"]["coloncclose"],
    "ascript" => 'keystroke ":ccl" & return',
  },
  #'tabs.title'
  {
    "key"  => ":tabnew or :tabnew file",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["coloncclose"],
    "ascript" => 'keystroke ":tabnew"//key code 49//keystroke "file" & return',
  },
  {
    "key"  => "Ctrl+wT",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["ctrlPluswT"],
    "ascript" => 'keystroke "w" using control down//keystroke "T"',
  },
  {
    "key"  => "gt or :tabn[ext]",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["gt"],
    "ascript" => 'keystroke "gt"',
  },
  {
    "key"  => "gT or :tabp[revious]",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["gT"],
    "ascript" => 'keystroke "gT"',
  },
  {
    "key"  => "#gt",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["hashgt"],
    "ascript" => 'keystroke "#gt"',
  },
  {
    "key"  => ":tabm[ove]",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["colontabmove"],
    "ascript" => 'keystroke ":tabm" & return',
  },
  {
    "key"  => ":tabc[lose]",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["colontabc"],
    "ascript" => 'keystroke ":tabc" & return',
  },
  {
    "key"  => ":tabo[nly]",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["colontabo"],
    "ascript" => 'keystroke ":tabo" & return',
  },
  {
    "key"  => ":tabdo command",
    "catcode"=> "tabs",
    "category"=> data["tabs"]["title"],
    "desc" => data["tabs"]["commands"]["colontabdo"],
    "ascript" => 'keystroke ":tabdo"//key code 49//keystroke "command"',
  },
  # 'workingWithMultipleFiles.title'
  {
    "key"  => ":e[dit] file",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colone"],
    "ascript" => 'keystroke ":e"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":bn[ext]",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonbnext"],
    "ascript" => 'keystroke ":bn" & return',
  },
  {
    "key"  => ":bp[revious]",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonbprev"],
    "ascript" => 'keystroke ":bp" & return',
  },
  {
    "key"  => ":bd[elete]",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonbd"],
    "ascript" => 'keystroke ":bd" & return',
  },
  {
    "key"  => ":b[uffer]#",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonbnumber"],
    "ascript" => 'keystroke ":b#"',
  },
  {
    "key"  => ":b[uffer] file",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonbfile"],
    "ascript" => 'keystroke ":b"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":ls or :buffers",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonls"],
    "ascript" => 'keystroke ":ls" & return',
  },
  {
    "key"  => ":sp[lit] file",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonsp"],
    "ascript" => 'keystroke ":sp"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":vs[plit] file",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonvsp"],
    "ascript" => 'keystroke ":vs"//key code 49//keystroke "file"',
  },
  {
    "key"  => ":vert[ical] ba[ll]",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colonvertba"],
    "ascript" => 'keystroke ":vert"//key code 49//keystroke "ba" & return',
  },
  {
    "key"  => ":tab ba[ll]",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["colontabba"],
    "ascript" => 'keystroke ":tab"//key code 49//keystroke "ba" & return',
  },
  {
    "key"  => "Ctrl+w s",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusws"],
    "ascript" => 'keystroke "w" using control down//keystroke "s"',
  },
  {
    "key"  => "Ctrl+w v",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswv"],
    "ascript" => 'keystroke "w" using control down//keystroke "v"',
  },
  {
    "key"  => "Ctrl+w w",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusww"],
    "ascript" => 'keystroke "w" using control down//keystroke "w"',
  },
  {
    "key"  => "Ctrl+w q",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswq"],
    "ascript" => 'keystroke "w" using control down//keystroke "q"',
  },
  {
    "key"  => "Ctrl+w x",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswx"],
    "ascript" => 'keystroke "w" using control down//keystroke "x"',
  },
  {
    "key"  => "Ctrl+w =",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPlusw="],
    "ascript" => 'keystroke "w" using control down//keystroke "="',
  },
  {
    "key"  => "Ctrl+w h",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswh"],
    "ascript" => 'keystroke "w" using control down//keystroke "h"',
  },
  {
    "key"  => "Ctrl+w l",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswl"],
    "ascript" => 'keystroke "w" using control down//keystroke "l"',
  },
  {
    "key"  => "Ctrl+w j",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswj"],
    "ascript" => 'keystroke "w" using control down//keystroke "j"',
  },
  {
    "key"  => "Ctrl+w k",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswk"],
    "ascript" => 'keystroke "w" using control down//keystroke "k"',
  },
  {
    "key"  => "Ctrl+w H",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswH"],
    "ascript" => 'keystroke "w" using control down//keystroke "H"',
  },
  {
    "key"  => "Ctrl+w L",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswL"],
    "ascript" => 'keystroke "w" using control down//keystroke "L"',
  },
  {
    "key"  => "Ctrl+w J",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswJ"],
    "ascript" => 'keystroke "w" using control down//keystroke "J"',
  },
  {
    "key"  => "Ctrl+w K",
    "catcode"=> "workingWithMultipleFiles",
    "category"=> data["workingWithMultipleFiles"]["title"],
    "desc" => data["workingWithMultipleFiles"]["commands"]["ctrlPluswK"],
    "ascript" => 'keystroke "w" using control down//keystroke "K"',
  },
  # 'diff.title'
  {
    "key"  => "zf",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zf"],
    "ascript" => 'keystroke "zf"',
  },
  {
    "key"  => "zd",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zd"],
    "ascript" => 'keystroke "zd"',
  },
  {
    "key"  => "za",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["za"],
    "ascript" => 'keystroke "za"',
  },
  {
    "key"  => "zo",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zo"],
    "ascript" => 'keystroke "zo"',
  },
  {
    "key"  => "zc",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zc"],
    "ascript" => 'keystroke "zc"',
  },
  {
    "key"  => "zr",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zr"],
    "ascript" => 'keystroke "zr"',
  },
  {
    "key"  => "zm",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zm"],
    "ascript" => 'keystroke "zm"',
  },
  {
    "key"  => "zi",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["zi"],
    "ascript" => 'keystroke "zi"',
  },
  {
    "key"  => "]c",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["closeSquarec"],
    "ascript" => 'keystroke "]c"',
  },
  {
    "key"  => "[c",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["openSquarec"],
    "ascript" => 'keystroke "[c"',
  },
  {
    "key"  => "do or :diffg[et]",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["do"],
    "ascript" => 'keystroke "do"',
  },
  {
    "key"  => "dp or :diffpu[t]",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["dp"],
    "ascript" => 'keystroke "dp"',
  },
  {
    "key"  => ":diffthis",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["colonDiffthis"],
    "ascript" => 'keystroke ":diffthis" & return',
  },
  {
    "key"  => ":dif[fupdate]",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["colonDiffupdate"],
    "ascript" => 'keystroke ":dif" & return',
  },
  {
    "key"  => ":diffo[ff]",
    "catcode"=> "diff",
    "category"=> data["diff"]["title"],
    "desc" => data["diff"]["commands"]["colonDiffoff"],
    "ascript" => 'keystroke ":diffo" & return',
  },
  # spell
  {
    "key"  => ":set spell spelllang=en_us",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["setSpellEnUs"],
    "ascript" => 'keystroke ":set"//key code 49//keystroke "spell"//key code 49//keystroke "spelllang=en_us" & return',
  },
  {
    "key"  => ":set nospell",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["setNoSpell"],
    "ascript" => 'keystroke ":set"//key code 49//keystroke "nospell" & return',
  },
  {
    "key"  => "]s",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["closeBrackets"],
    "ascript" => 'keystroke "]s"',
  },
  {
    "key"  => "[s",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["openBrackets"],
    "ascript" => 'keystroke "[s"',
  },
  {
    "key"  => "z=",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["z="],
    "ascript" => 'keystroke "z="',
  },
  {
    "key"  => "zg",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["zg"],
    "ascript" => 'keystroke "zg"',
  },
  {
    "key"  => "zw",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["zw"],
    "ascript" => 'keystroke "zw"',
  },
  {
    "key"  => "zu",
    "catcode"=> "spell",
    "category"=> data["spell"]["title"],
    "desc" => data["spell"]["commands"]["zu"],
    "ascript" => 'keystroke "zu"',
  },
  # misc
  {
    "key"  => "Ctrl+a",
    "catcode"=> "misc",
    "category"=> data["misc"]["title"],
    "desc" => data["misc"]["commands"]["Ctrla"],
    "ascript" => 'keystroke "a" using control down',
  },
  {
    "key"  => "Ctrl+x",
    "catcode"=> "misc",
    "category"=> data["misc"]["title"],
    "desc" => data["misc"]["commands"]["Ctrlx"],
    "ascript" => 'keystroke "x" using control down',
  },
  {
    "key"  => "gv",
    "catcode"=> "misc",
    "category"=> data["misc"]["title"],
    "desc" => data["misc"]["commands"]["gv"],
    "ascript" => 'keystroke "gv"'
  },

]

items = []
vim_cheatsheet.each do |v|
  item = {
    "title": "#{v['desc']}".capitalize,
    "subtitle": "#{v['category']} #{separator} #{v['key']}",
    "arg": [v['ascript']],
    "icon": {
      "type": "file",
      "path": File.join(dcurrent, "img", "#{v['catcode']}.png")
    }
  }
  item["uid"] = v['catcode'] + "-" + v['category'] unless fixed_order
  items << item
end

result = {"items" => items}.to_json
print result
